export const data = JSON.parse("{\"key\":\"v-20aec9ab\",\"path\":\"/topics/plastic.html\",\"title\":\"Plastics\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Plastics\",\"index\":true,\"icon\":\"info\",\"author\":\"G.Willson\",\"description\":\"Good sorting and proper management of waste stream-derived plastics are crucial for efficient and environmentally friendly pyrolysis-based fuel production. Pyrolysis is a thermo...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://scdhub-vuepress.vercel.app/topics/plastic.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"SCD Hub\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Plastics\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Good sorting and proper management of waste stream-derived plastics are crucial for efficient and environmentally friendly pyrolysis-based fuel production. Pyrolysis is a thermo...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"G.Willson\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Plastics\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"G.Willson\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Importance of good sorting in pyrolysis:\",\"slug\":\"importance-of-good-sorting-in-pyrolysis\",\"link\":\"#importance-of-good-sorting-in-pyrolysis\",\"children\":[]},{\"level\":2,\"title\":\"Dangers of using poorly sorted waste stream-derived plastics for pyrolysis:\",\"slug\":\"dangers-of-using-poorly-sorted-waste-stream-derived-plastics-for-pyrolysis\",\"link\":\"#dangers-of-using-poorly-sorted-waste-stream-derived-plastics-for-pyrolysis\",\"children\":[]},{\"level\":2,\"title\":\"Plastics Upcycling\",\"slug\":\"plastics-upcycling\",\"link\":\"#plastics-upcycling\",\"children\":[]},{\"level\":2,\"title\":\"Open Burn Abatement\",\"slug\":\"open-burn-abatement\",\"link\":\"#open-burn-abatement\",\"children\":[]},{\"level\":2,\"title\":\"Health Benefits:\",\"slug\":\"health-benefits\",\"link\":\"#health-benefits\",\"children\":[]},{\"level\":2,\"title\":\"Jobs Created:\",\"slug\":\"jobs-created\",\"link\":\"#jobs-created\",\"children\":[]},{\"level\":2,\"title\":\"Choosing Strategies for Maximum Community Empowerment in Waste Management\",\"slug\":\"choosing-strategies-for-maximum-community-empowerment-in-waste-management\",\"link\":\"#choosing-strategies-for-maximum-community-empowerment-in-waste-management\",\"children\":[]}],\"readingTime\":{\"minutes\":5.96,\"words\":1789},\"filePathRelative\":\"topics/plastic.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
